### ISSUE TITLE
error with command twscrape login_accounts

### ISSUE THREAD

**Issue by feesgo** [vladkens/twscrape#111]
I run the command:

twscrape add_accounts ./accounts.txt username:password:email:email_password:cookies

The result was:

2024-01-17 13:41:16.484 | INFO     | twscrape.db:migrate:86 - Running migration to v1
2024-01-17 13:41:16.500 | INFO     | twscrape.db:migrate:86 - Running migration to v2
2024-01-17 13:41:16.515 | INFO     | twscrape.db:migrate:86 - Running migration to v3
2024-01-17 13:41:16.515 | INFO     | twscrape.accounts_pool:add_account:97 - Account MY_TWITTER_ACCOUNT added successfully (active=False)

Then I run the command:

twscrape login_accounts

And then appear this error:

2024-01-17 13:41:39.631 | INFO     | twscrape.accounts_pool:login_all:155 - [1/1] Logging in MY_TWITTER_ACCOUNT - MY_EMAIL
2024-01-17 13:41:40.456 | ERROR    | twscrape.accounts_pool:login:141 - Error logging in to MY_TWITTER_ACCOUNT: 'ct0'
{'total': 1, 'success': 0, 'failed': 1}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F78C198670>
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

And twscrape no longer works...

**Comment by feesgo** [comment]
Sorry!

My error!

I changed my twitter password but I dont update the file:

accounts.txt
