### ISSUE TITLE
search tweets dont work when built docker container

### ISSUE THREAD

**Issue by votienBac** [vladkens/twscrape#51]
My dockerfile:
```
FROM python:3.10-bullseye
WORKDIR /app
COPY stopwords.txt /app/stopwords.txt
RUN mkdir /app/uploads
COPY requirements.txt .
RUN pip install git+https://github.com/JustAnotherArchivist/snscrape.git
RUN pip install git+https://github.com/vladkens/twscrape.git
RUN pip install flask[async]
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install logstash
EXPOSE 5000
CMD ["python", "app.py"]
```

On my laptop, everything is working file but when I dockerize on vps ubuntu 20.04, it not working
**Get accounts is working fine but search throw exeption:**

```
Traceback (most recent call last):
  File "/app/twscrape_test.py", line 179, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/twscrape_test.py", line 14, in main
    followings = await gather(api.following(user_id))
  File "/usr/local/lib/python3.10/site-packages/twscrape/utils.py", line 16, in gather
    async for x in gen:
  File "/usr/local/lib/python3.10/site-packages/twscrape/api.py", line 188, in following
    async for rep in self.following_raw(uid, limit=limit, kv=kv):
  File "/usr/local/lib/python3.10/site-packages/twscrape/api.py", line 184, in following_raw
    async for x in self._gql_items(op, kv, limit=limit):
  File "/usr/local/lib/python3.10/site-packages/twscrape/api.py", line 63, in _gql_items
    obj = rep.json()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Comment by entasadar** [comment]
I had the same problem with `tweet_details` on Debian based images. After debugging I found that httpx can't decode brotli (`content-encoding: br`). 
The solution that worked for me is very simple - just add the brotli package to your requirements.txt.
Try doing the same, it might help:)
